### PR TITLE
Fix for SSRF vulnerability

### PR DESCRIPTION
**Pull request by AbdurrahmanA**
https://github.com/ospfranco/link-preview-js/issues/105

@ospfranco Can we have a chance to check the url with regex before the redirect? So maybe that way library can check even if `followRedirects:true`

### CODE REVIEW

**Comment by ospfranco** [comment]
Not sure if it is possible, since at that point the fetch API has taken over, I guess we would need to manually do the requests for redirects... I don't have the time to do such a large feature though

**Comment by ospfranco** [comment]
Would you mind fixing the failing test? and also adding one more test for erroring when follow redirects is off

**Comment by ospfranco** [comment]
Do another test with the redirection flag set to false please :)

**Comment by AbdurrahmanA** [comment]
> 

Will be ready soon 😊

**Comment by ospfranco** [comment]
Weird, a couple of other tests broke with a redirection error on the latest run, but not in the first one, any idea why?

**Comment by AbdurrahmanA** [comment]
interesting, maybe cause github actions server proxy config

**Comment by ospfranco** [comment]
released under 2.1.13, thanks for the PR

**Comment by AbdurrahmanA** [comment]
Thank you so much for attention 👍

**Pull request merged**
